module.exports = {
	extends: 'stylelint-config-recommended',
	plugins: [ '@stylistic/stylelint-plugin' ],
	rules: {
		'no-descending-specificity': null,

		'color-named': 'never',
		'shorthand-property-no-redundant-values': true,
		'declaration-block-no-redundant-longhand-properties': true,
		'declaration-block-single-line-max-declarations': 1,
		'@stylistic/selector-max-empty-lines': 0,

		'@stylistic/color-hex-case': 'lower',
		'color-hex-length': 'short',
		'font-family-name-quotes': 'always-where-recommended',
		'font-weight-notation': 'numeric',
		'@stylistic/function-comma-newline-after': 'always-multi-line',
		'@stylistic/function-comma-newline-before': 'never-multi-line',
		'@stylistic/function-comma-space-after': 'always-single-line',
		'@stylistic/function-comma-space-before': 'never',
		'@stylistic/function-max-empty-lines': 0,
		'@stylistic/function-parentheses-newline-inside': 'always-multi-line',
		'@stylistic/function-parentheses-space-inside': 'never',
		'function-url-quotes': 'always',
		'@stylistic/function-whitespace-after': 'always',
		'@stylistic/number-leading-zero': 'never',
		'@stylistic/string-quotes': 'double',
		'length-zero-no-unit': true,
		'@stylistic/unit-case': 'lower',
		'@stylistic/value-list-comma-newline-after': 'always-multi-line',
		'@stylistic/value-list-comma-newline-before': 'never-multi-line',
		'@stylistic/value-list-comma-space-after': 'always-single-line',
		'@stylistic/value-list-comma-space-before': 'never',
		'@stylistic/value-list-max-empty-lines': 0,
		'custom-property-empty-line-before': 'never',
		'@stylistic/property-case': 'lower',
		'@stylistic/declaration-bang-space-after': 'never',
		'@stylistic/declaration-bang-space-before': 'always',
		'@stylistic/declaration-colon-newline-after': 'always-multi-line',
		'@stylistic/declaration-colon-space-after': 'always-single-line',
		'@stylistic/declaration-colon-space-before': 'never',
		'declaration-empty-line-before': 'never',
		'@stylistic/declaration-block-semicolon-newline-after': 'always-multi-line',
		'@stylistic/declaration-block-semicolon-newline-before': 'never-multi-line',
		'@stylistic/declaration-block-semicolon-space-after': 'always-single-line',
		'@stylistic/declaration-block-semicolon-space-before': 'never',
		'@stylistic/declaration-block-trailing-semicolon': 'always',
		'@stylistic/block-closing-brace-empty-line-before': 'never',
		'@stylistic/block-closing-brace-newline-after': 'always',
		'@stylistic/block-closing-brace-newline-before': 'always-multi-line',
		'@stylistic/block-closing-brace-space-after': 'always-single-line',
		'@stylistic/block-closing-brace-space-before': 'always-single-line',
		'@stylistic/block-opening-brace-newline-after': 'always-multi-line',
		'@stylistic/block-opening-brace-space-after': 'always-single-line',
		'@stylistic/block-opening-brace-space-before': 'always',
		'@stylistic/selector-attribute-brackets-space-inside': 'never',
		'@stylistic/selector-attribute-operator-space-after': 'never',
		'@stylistic/selector-attribute-operator-space-before': 'never',
		'selector-attribute-quotes': 'always',
		'@stylistic/selector-combinator-space-after': 'always',
		'@stylistic/selector-combinator-space-before': 'always',
		'@stylistic/selector-descendant-combinator-no-non-space': true,
		'@stylistic/selector-pseudo-class-case': 'lower',
		'@stylistic/selector-pseudo-class-parentheses-space-inside': 'never',
		'@stylistic/selector-pseudo-element-case': 'lower',
		'selector-pseudo-element-colon-notation': 'single',
		'selector-type-case': 'lower',
		'@stylistic/selector-list-comma-newline-before': 'never-multi-line',
		'@stylistic/selector-list-comma-space-after': 'always-single-line',
		'@stylistic/selector-list-comma-space-before': 'never',
		'rule-empty-line-before': [
			'always-multi-line',
			{
				except: [ 'first-nested' ],
				ignore: [ 'after-comment' ],
			},
		],
		'@stylistic/media-feature-colon-space-after': 'always',
		'@stylistic/media-feature-colon-space-before': 'never',
		'@stylistic/media-feature-name-case': 'lower',
		'@stylistic/media-feature-parentheses-space-inside': 'never',
		'@stylistic/media-feature-range-operator-space-after': 'always',
		'@stylistic/media-feature-range-operator-space-before': 'always',
		'@stylistic/media-query-list-comma-newline-after': 'always-multi-line',
		'@stylistic/media-query-list-comma-newline-before': 'never-multi-line',
		'@stylistic/media-query-list-comma-space-after': 'always',
		'@stylistic/media-query-list-comma-space-before': 'never',
		'at-rule-empty-line-before': [
			'always',
			{
				except: [ 'first-nested' ],
				ignore: [ 'after-comment', 'blockless-after-same-name-blockless' ],
			},
		],
		'@stylistic/at-rule-name-case': 'lower',
		'@stylistic/at-rule-name-space-after': 'always',
		'@stylistic/at-rule-semicolon-newline-after': 'always',
		'@stylistic/at-rule-semicolon-space-before': 'never',
		'comment-empty-line-before': 'always',
		'comment-whitespace-inside': 'always',
		'@stylistic/indentation': 'tab',
		'@stylistic/linebreaks': 'unix',
		'@stylistic/max-empty-lines': 1,
		'@stylistic/no-extra-semicolons': true,
		'@stylistic/no-eol-whitespace': true,
		'@stylistic/no-missing-end-of-source-newline': true,
	},
};
